# Generated by Django 3.0.5 on 2020-04-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_backend', '0005_delete_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInterviewStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer', models.CharField(max_length=200, verbose_name='ผู้สัมภาษณ์')),
                ('interview_at', models.DateField(auto_now_add=True, verbose_name='วันที่')),
            ],
        ),
        migrations.CreateModel(
            name='FormRegisterStartup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regis_name', models.CharField(max_length=200, verbose_name='ผู้สมัคร')),
                ('regis_at', models.DateField(auto_now_add=True, verbose_name='วันที่สมัคร')),
                ('tsic_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='เลข tsic')),
            ],
        ),
        migrations.CreateModel(
            name='StartupCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'รอตรวจคุณสมบัติ'), (2, 'ผ่านตรวจคุณสมบัติ'), (3, 'ไม่ผ่านตรวจคุณสมบัติ'), (4, 'ผ่านตรวจประเมิน'), (5, 'ไม่ผ่านตรวจประเมิน'), (6, 'ผ่านสัมภาษณ์'), (7, 'ไม่ผ่านสัมภาษณ์'), (8, 'ผ่านการพิจารณา'), (9, 'ไม่ผ่านการพิจารณา'), (10, 'ได้รับรางวัล')], default=1, verbose_name='สถานะการประกวด')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Competition')),
                ('enterpise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Enterpise')),
                ('form_interview', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_startup4.FormInterviewStartup')),
                ('form_register', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_startup4.FormRegisterStartup')),
            ],
        ),
    ]
