# Generated by Django 3.0.5 on 2020-04-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_startup4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupcompetition',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'รอตรวจคุณสมบัติ'), (2, 'ผ่านตรวจคุณสมบัติ'), (3, 'ไม่ผ่านตรวจคุณสมบัติ'), (4, 'ผ่านตรวจประเมิน'), (5, 'ไม่ผ่านตรวจประเมิน'), (6, 'ผ่านสัมภาษณ์'), (7, 'ไม่ผ่านสัมภาษณ์'), (8, 'ผ่านการพิจารณา'), (9, 'ไม่ผ่านการพิจารณา')], default=1, verbose_name='สถานะการประกวด'),
        ),
    ]
