# Generated by Django 3.0.5 on 2020-04-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0002_auto_20200422_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smecompetition',
            name='form_interview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.FormInterview'),
        ),
        migrations.AlterField(
            model_name='smecompetition',
            name='form_register',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.FormRegister'),
        ),
        migrations.AlterField(
            model_name='smecompetition',
            name='form_site_visit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.FormSiteVisit'),
        ),
    ]
