# Generated by Django 3.0.5 on 2020-04-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0003_auto_20200422_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formregister',
            name='regis_at',
        ),
        migrations.AddField(
            model_name='formregister',
            name='agreement',
            field=models.BooleanField(blank=True, null=True, verbose_name='ยินยอมข้อตกลง'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='employ',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='จำนวนการจ้างงาน'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='news_from',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับข่าวสารจากช่องทาง'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='news_from_etc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับข่าวสารจากช่องทางอื่นๆ'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='กำไร'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='regis_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสมัคร'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='regis_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สมัคร'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='revenue',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รายได้ต่อปี'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='train_or_contest',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลือกอบรมหรือประกวด'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee1_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลผู้เข้าอบรมคนที่1'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee1_id_card',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขบัตรประชาชนผู้เข้าอบรมคนที่1'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee1_mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เบอร์มิอถือผู้เข้าอบรมคนที่1'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee1_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้เข้าอบรมคนที่1'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee2_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลผู้เข้าอบรมคนที่2'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee2_id_card',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขบัตรประชาชนผู้เข้าอบรมคนที่2'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee2_mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เบอร์มิอถือผู้เข้าอบรมคนที่2'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='trainee2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้เข้าอบรมคนที่2'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='training_course',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หลักสูตรอบรม'),
        ),
        migrations.AlterField(
            model_name='formregister',
            name='regis_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ผู้สมัคร'),
        ),
        migrations.AlterField(
            model_name='smecompetition',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'รอตรวจคุณสมบัติ'), (2, 'ผ่านตรวจคุณสมบัติ'), (3, 'ไม่ผ่านตรวจคุณสมบัติ'), (4, 'ผ่านตรวจประเมิน'), (5, 'ไม่ผ่านตรวจประเมิน'), (6, 'ผ่านสัมภาษณ์'), (7, 'ไม่ผ่านสัมภาษณ์'), (8, 'ผ่านการพิจารณา'), (9, 'ไม่ผ่านการพิจารณา'), (10, 'เข้าชิงรางวัล')], default=1, verbose_name='สถานะการประกวด'),
        ),
    ]
