# Generated by Django 3.0.5 on 2020-04-24 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_delete_contest'),
        ('app_sme12', '0004_auto_20200424_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smecompetition',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Competition'),
        ),
        migrations.AlterField(
            model_name='smecompetition',
            name='enterpise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Enterpise'),
        ),
    ]
