# Generated by Django 3.0.5 on 2020-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0005_auto_20200424_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formregister',
            name='regis_code',
            field=models.CharField(max_length=20, verbose_name='รหัสสมัคร'),
        ),
    ]
