# Generated by Django 3.0.5 on 2020-04-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0006_auto_20200428_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formregister',
            name='train_or_contest',
        ),
        migrations.AddField(
            model_name='formregister',
            name='join_choice',
            field=models.PositiveSmallIntegerField(choices=[(1, 'สนใจเข้ารับการฝึกอบรมและเข้าร่วมประกวดรางวัล'), (2, 'สนใจเฉพาะการเข้าร่วมประกวดรางวัล'), (3, 'สนใจเข้ารับการฝึกอบรม')], default=2, verbose_name='เลือกอบรมหรือประกวด'),
        ),
    ]
