# Generated by Django 3.0.5 on 2020-05-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0009_employment_agriculture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='agriculture',
        ),
        migrations.AddField(
            model_name='formregister',
            name='employment_etc',
            field=models.IntegerField(blank=True, max_length=40, null=True, verbose_name='จำนวนจ้างสำหรับธุรกิจเกษตร'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='revenue_etc',
            field=models.IntegerField(blank=True, max_length=40, null=True, verbose_name='รายได้สำหรับธุรกิจเกษตร'),
        ),
    ]
