# Generated by Django 3.0.5 on 2020-05-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0010_auto_20200502_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formregister',
            name='employment_etc',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนจ้างสำหรับธุรกิจเกษตร'),
        ),
        migrations.AlterField(
            model_name='formregister',
            name='revenue_etc',
            field=models.IntegerField(blank=True, null=True, verbose_name='รายได้สำหรับธุรกิจเกษตร'),
        ),
    ]
