# Generated by Django 3.0.5 on 2020-05-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0011_auto_20200502_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizeCapital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัส')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitPrevious',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัส')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
            ],
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='profit',
        ),
        migrations.AddField(
            model_name='formregister',
            name='authorize_capital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.AuthorizeCapital'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='profit_previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.ProfitPrevious'),
        ),
    ]
