# Generated by Django 3.0.5 on 2020-05-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0012_auto_20200503_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ช่องทาง')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัส')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
            ],
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='news_from',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='news_from_etc',
        ),
        migrations.AddField(
            model_name='formregister',
            name='promote_etc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='รับข่าวสารจากช่องทางอื่นๆ'),
        ),
        migrations.AlterField(
            model_name='authorizecapital',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ทุนจดทะเบียน'),
        ),
        migrations.AlterField(
            model_name='profitprevious',
            name='name',
            field=models.CharField(max_length=100, verbose_name='กำไร'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='promote',
            field=models.ManyToManyField(blank=True, null=True, to='app_sme12.Promote'),
        ),
    ]
