# Generated by Django 3.0.5 on 2020-05-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0013_auto_20200503_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='หลักสูตร')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัส')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
            ],
        ),
        migrations.CreateModel(
            name='RegisChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ตัวเลือก')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัส')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
            ],
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='join_choice',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='training_course',
        ),
        migrations.AlterField(
            model_name='formregister',
            name='promote',
            field=models.ManyToManyField(to='app_sme12.Promote'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.Course'),
        ),
        migrations.AddField(
            model_name='formregister',
            name='regis_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_sme12.RegisChoice'),
        ),
    ]
