# Generated by Django 3.0.5 on 2020-05-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0014_auto_20200503_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formregister',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='course',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='regis_choice',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee1_email',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee1_id_card',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee1_mobile',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee1_name',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee2_email',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee2_id_card',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee2_mobile',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='trainee2_name',
        ),
        migrations.RemoveField(
            model_name='formregister',
            name='tsic_no',
        ),
        migrations.AlterField(
            model_name='smecompetition',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'รอตรวจคุณสมบัติ'), (2, 'ผ่านตรวจคุณสมบัติ'), (3, 'ไม่ผ่านตรวจคุณสมบัติ'), (4, 'ผ่านตรวจประเมิน'), (5, 'ไม่ผ่านตรวจประเมิน'), (6, 'ผ่านสัมภาษณ์'), (7, 'ไม่ผ่านสัมภาษณ์'), (8, 'ผ่านการพิจารณา'), (9, 'ไม่ผ่านการพิจารณา'), (10, 'เข้าชิงรางวัล'), (11, 'ไม่เข้าชิงรางวัล')], default=1, verbose_name='สถานะการประกวด'),
        ),
    ]
