# Generated by Django 3.0.5 on 2020-05-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0015_auto_20200507_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score1',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 1'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score2',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 2'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score3',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 3'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score4',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 4'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score5',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 5'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score6',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 6'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='site_score7',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนหมวดที่ 7'),
        ),
    ]
