# Generated by Django 3.0.5 on 2020-05-08 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_remove_enterpise_regis_cap'),
        ('app_sme12', '0016_auto_20200508_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsitevisit',
            name='enterpise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Enterpise'),
        ),
    ]
