# Generated by Django 3.0.5 on 2020-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0017_formsitevisit_enterpise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score1',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 1 บทบาทของผู้บริหารในการนำองค์กร'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score2',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 2. การวางแผนการดำเนินธุรกิจ'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score3',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 3. การมุ่งเน้นลูกค้าและตลาด'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score4',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 4. การวัด วิเคราะห์และจัดการความรู้'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score5',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 5. การบริหารทรัพยากรบุคคล'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score6',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 6. การจัดการกระบวนการ'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='site_score7',
            field=models.IntegerField(blank=True, null=True, verbose_name='หมวดที่ 7. ผลลัพธ์ทางธุรกิจ'),
        ),
        migrations.AlterField(
            model_name='formsitevisit',
            name='visiter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ผู้ไปเยี่ยมชม'),
        ),
    ]
