# Generated by Django 3.0.5 on 2020-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0018_auto_20200508_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsitevisit',
            name='visit_summary',
            field=models.BooleanField(default=True, verbose_name='สรุปผลการลงคะแนน'),
        ),
    ]
