# Generated by Django 3.0.5 on 2020-05-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0019_formsitevisit_visit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='จำนวนการจ้างงาน(ย่อ)'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รายได้ต่อปี(ย่อ)'),
        ),
    ]
