# Generated by Django 3.0.5 on 2020-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sme12', '0021_auto_20200523_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminterview',
            name='score_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนรวม'),
        ),
        migrations.AddField(
            model_name='formsitevisit',
            name='score_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='คะแนนรวม'),
        ),
    ]
