# Generated by Django 3.0.5 on 2020-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อรางวัล')),
                ('name_eng', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อรางวัล eng')),
                ('active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
            ],
        ),        
    ]
