# Generated by Django 3.0.5 on 2020-04-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0002_auto_20200422_0326'),
    ]

    operations = [
        
    ]
