# Generated by Django 3.0.5 on 2020-04-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0004_delete_contest'),
    ]

    operations = [
       
    ]
