# Generated by Django 3.0.5 on 2020-04-24 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0005_delete_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amphur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='รหัสอำเภอ')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออำเภอ')),
                ('postcode', models.CharField(max_length=20, verbose_name='รหัสไปรษณีย์')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อเจ้าของ')),
                ('card_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='เลขบัตรเจ้าของ')),
                ('address_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่')),
                ('mu', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมู่')),
                ('soi', models.CharField(blank=True, max_length=100, null=True, verbose_name='ซอย')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='ถนน')),
                ('postcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='รหัสไปรษณีย์')),
                ('tel', models.CharField(blank=True, max_length=200, null=True, verbose_name='เบอร์ติดต่อเจ้าของ')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='แฟกซ์ติดต่อเจ้าของ')),
                ('mobile', models.CharField(blank=True, max_length=200, null=True, verbose_name='เบอร์มือถือติดต่อเจ้าของ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลติดต่อเจ้าของ')),
                ('amphur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Amphur')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='รหัสจังหวัด')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อจังหวัด')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อภูมิภาค')),
            ],
        ),
        migrations.CreateModel(
            name='Tumbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='รหัสตำบล')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อตำบล')),
                ('amphur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Amphur')),
            ],
        ),        
        migrations.RemoveField(
            model_name='enterpise',
            name='owner_card_id',
        ),
        migrations.RemoveField(
            model_name='enterpise',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='enterpise',
            name='address_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขที่'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='business_group_etc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='กลุ่มธุรกิจอื่นๆ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.BusinessType'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='contact_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่งผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เบอร์ผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='แฟกซ์ติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='material',
            field=models.TextField(blank=True, null=True, verbose_name='วัตถุดิบในการผลิต'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='mu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมู่'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='otop',
            field=models.BooleanField(blank=True, null=True, verbose_name='มีการผลิตสินค้า OTOP หรือไม่'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='postcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='product_info',
            field=models.TextField(blank=True, null=True, verbose_name='ระบุสินค้า ยี่ห้อ และบริการโดยละเอียด'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='regis_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ทุนจดทะเบียน'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='soi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ซอย'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ถนน'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='tel',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='เบอร์ติดต่อ'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='เว็บไซต์ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='enterpise',
            name='establish_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันก่อตั้งกิจการ'),
        ),
        migrations.AlterField(
            model_name='enterpise',
            name='sme_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสสมาชิก สสว.'),
        ),
        migrations.AlterField(
            model_name='enterpise',
            name='sme_connext_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสสมาชิก sme connext.'),
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Region'),
        ),
        migrations.AddField(
            model_name='owner',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Province'),
        ),
        migrations.AddField(
            model_name='owner',
            name='tumbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Tumbol'),
        ),
        migrations.AddField(
            model_name='amphur',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Province'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='amphur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Amphur'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Owner'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Province'),
        ),
        migrations.AddField(
            model_name='enterpise',
            name='tumbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_backend.Tumbol'),
        ),
    ]
