# Generated by Django 3.0.5 on 2020-04-24 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0006_auto_20200424_0355'),
    ]

    operations = [
        
    ]
