# Generated by Django 3.0.5 on 2020-04-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0007_delete_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อเจ้าของ'),
        ),
    ]
