# Generated by Django 3.0.5 on 2020-04-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0009_businessmodel_model_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='รหัส'),
        ),
    ]
