# Generated by Django 3.0.5 on 2020-05-03 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0010_businessmodel_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterpise',
            name='regis_cap',
        ),
    ]
