# Generated by Django 3.0.5 on 2020-05-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0011_remove_enterpise_regis_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpise',
            name='tsic_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลข tsic'),
        ),
    ]
